# ======================================
# 🚗 MotorPride Kenya - Netlify Config
# ======================================

[build]
  # ✅ FIXED: Simple build command that works
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# ======================================
# 🔀 SPA Routing & Redirects
# ======================================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ======================================
# 🔒 CORS & JSON Headers
# ======================================
[[headers]]
  for = "/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"

# ======================================
# ⚡ Performance Optimizations
# ======================================
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
