backend:
  name: git-gateway
  branch: main   # or master depending on your repo default branch

media_folder: "static/uploads"    # where uploaded images will go
public_folder: "/uploads"

collections:
  - name: "featured_cars"
    label: "Featured Cars"
    folder: "content/featured_cars"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "available_units"
    label: "Available Units"
    folder: "content/available_units"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Car Name", name: "car_name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Fuel Type", name: "fuel", widget: "string" }
      - { label: "Images", name: "images", widget: "list", field: {label: Image, name: image, widget: image} }

  - name: "car_hire"
    label: "Car Hire"
    folder: "content/car_hire"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Package Name", name: "package_name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Comment", name: "comment", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }
