backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

locale: 'en'

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "cars"
    label: "Cars"
    folder: "content/cars"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Brand", name: "brand", widget: "string", required: true }
      - { label: "Model", name: "model", widget: "string", required: true }
      - { label: "Year", name: "year", widget: "number", required: true }
      - { label: "Price", name: "price", widget: "string", required: true }
      - { 
          label: "Status", 
          name: "status", 
          widget: "select", 
          options: ["available", "sold", "incoming"],
          default: "available",
          required: true 
        }
      - { 
          label: "Featured", 
          name: "featured", 
          widget: "boolean", 
          default: false 
        }
      - { 
          label: "Description", 
          name: "description", 
          widget: "markdown",
          required: true 
        }
      - { 
          label: "Features", 
          name: "features", 
          widget: "list",
          field: { label: "Feature", name: "feature", widget: "string" },
          required: false 
        }
      - { 
          label: "Images", 
          name: "images", 
          widget: "list", 
          field: { label: "Image", name: "image", widget: "image" },
          required: true 
        }

  - name: "contacts"
    label: "Contacts"
    folder: "content/contacts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Phone", name: "phone", widget: "string", required: true }
      - { label: "WhatsApp", name: "whatsapp", widget: "string", required: true }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { 
          label: "Role", 
          name: "role", 
          widget: "select",
          options: ["Sales Agent", "Manager", "Support", "Admin"],
          default: "Sales Agent",
          required: true 
        }