backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "available_units"
    label: "Available Units"
    folder: "content/available_units"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Car Name", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Fuel Type", name: "fuel", widget: "string"}
      - {label: "Transmission", name: "transmission", widget: "string"}
      - {label: "Main Image", name: "main_image", widget: "image"}
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}}

  - name: "featured_cars"
    label: "Featured Cars"
    folder: "content/featured_cars"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Car Name", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "main_image", widget: "image"}
