backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cars"
    label: "Cars"
    folder: "content/cars"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Car Name", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "string" }
