backend:
  name: git-gateway
  branch: main

media_folder: "static/images/cars"
public_folder: "/images/cars"

collections:
  - name: "cars"
    label: "Cars"
    folder: "data/cars"
    create: true
    slug: "{{make}}-{{model}}-{{year}}"  # ← CHANGED THIS LINE
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Make", name: "make", widget: "string" }
      - { label: "Model", name: "model", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Fuel Type", name: "fuel", widget: "select", options: ["Petrol", "Diesel", "Hybrid", "Electric"] }
      - { label: "Transmission", name: "transmission", widget: "string" }
      - { label: "Engine", name: "engine", widget: "string" }
      - { label: "Mileage", name: "mileage", widget: "string" }
      - { label: "Color", name: "color", widget: "string" }
      - { label: "Body Type", name: "body", widget: "select", options: ["SUV", "Sedan", "Hatchback", "MPV", "Van"] }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Stock ID", name: "stockID", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Available", "Incoming", "Sold"], required: false }
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Features", name: "features", widget: "list", field: { label: "Feature", name: "feature", widget: "string" } }

  - name: "contacts"
    label: "Contacts"
    folder: "data/contacts"
    create: true
    slug: "{{name | slugify}}"  # ← CHANGED THIS TOO
    extension: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Number", name: "number", widget: "string" }