backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

# Enables editorial workflow (draft → review → publish)
publish_mode: editorial_workflow

# ✅ Replace with your live Netlify site URL
site_url: https://motorpridekenya.netlify.app
display_url: https://motorpridekenya.netlify.app

# ✅ Netlify Build Hook (triggers automatic rebuild when CMS content changes)
build_hook: https://api.netlify.com/build_hooks/68ff5402366de6cdc809ec3a

# Where uploaded images go (in your repo)
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "cars"
    label: "Cars"
    folder: "content/cars"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Brand", name: "brand", widget: "string" }
      - { label: "Model", name: "model", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["available", "sold", "incoming"] }
      - { label: "Featured", name: "featured", widget: "boolean" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Features", name: "features", widget: "list" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"

  - name: "contacts"
    label: "Contacts"
    folder: "content/contacts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string" }
      - { label: "WhatsApp", name: "whatsapp", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
