backend:
  name: git-gateway
  branch: main   # or "master" if your repo uses that

media_folder: "uploads"       # folder inside repo where images are stored
public_folder: "/uploads"     # how they are served on the site

collections:
  - name: "cars"
    label: "Used Cars"
    folder: "used-cars"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Car Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Fuel", name: "fuel", widget: "string" }
      - { label: "Transmission", name: "transmission", widget: "string" }
      - { label: "Engine", name: "engine", widget: "string" }
      - { label: "Mileage", name: "mileage", widget: "string" }
      - { label: "Color", name: "color", widget: "string" }
      - { label: "Features", name: "features", widget: "list", allow_add: true }
      - label: "Images"
        name: "images"
        widget: "list"
        field: { label: "Image URL", name: "url", widget: "string" }
